// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNR.Data;

namespace VNR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VNR.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KhoaHocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenKhoaHoc = "Front End"
                        },
                        new
                        {
                            Id = 2,
                            TenKhoaHoc = "Back End"
                        },
                        new
                        {
                            Id = 3,
                            TenKhoaHoc = "Dotnet Core"
                        });
                });

            modelBuilder.Entity("VNR.Entities.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenMonHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("MonHocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaHocId = 1,
                            MoTa = "Description Bootstrap",
                            TenMonHoc = "Bootstrap"
                        },
                        new
                        {
                            Id = 2,
                            KhoaHocId = 1,
                            MoTa = "Description Angular JS",
                            TenMonHoc = "Angular JS"
                        },
                        new
                        {
                            Id = 3,
                            KhoaHocId = 1,
                            MoTa = "Description Angular",
                            TenMonHoc = "Angular"
                        },
                        new
                        {
                            Id = 4,
                            KhoaHocId = 1,
                            MoTa = "Description React JS",
                            TenMonHoc = "React JS"
                        },
                        new
                        {
                            Id = 5,
                            KhoaHocId = 2,
                            MoTa = "Description Dotnet",
                            TenMonHoc = "Dotnet"
                        },
                        new
                        {
                            Id = 6,
                            KhoaHocId = 2,
                            MoTa = "Description ASP NET",
                            TenMonHoc = "ASP NET"
                        },
                        new
                        {
                            Id = 7,
                            KhoaHocId = 3,
                            MoTa = "Description Net Core",
                            TenMonHoc = "Net Core"
                        });
                });

            modelBuilder.Entity("VNR.Entities.MonHoc", b =>
                {
                    b.HasOne("VNR.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("MonHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("VNR.Entities.KhoaHoc", b =>
                {
                    b.Navigation("MonHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
